### ISSUE TITLE
How list up gtk themes? 

### ISSUE THREAD

**Issue by maru0123-2004** [TkinterEP/python-gttk#4]
How list up gtk themes?   
There are no docs for that...

**Comment by rdbende** [comment]
Seems like it's not implemented here, but you can use this Tcl call to get a tuple of the available Gtk themes
```python
widget.tk.call("ttk::theme::gttk::availableStyles")
```

**Comment by maru0123-2004** [comment]
Oh, it's good!
Thank you...!

**Comment by maru0123-2004** [comment]
```python
>>> import tkinter
>>> import gttk
>>> from tkinter import ttk
>>> root=tkinter.Tk()
>>> gttk=gttk.GTTK(root) 
>>> style=ttk.Style()
>>> style.theme_use("gttk") 
>>> gttk   
<gttk.GTTK object at 0x000001C88A9F9E80>
>>> root.tk.call("ttk::theme::gttk::availableStyles")   
''
```
I tried that. But it return empty string...

**Comment by rdbende** [comment]
Then I don't know 🤷‍♂.
For me it returns a tuple with the installed Gtk, themes that I have in `/usr/share/themes`
```python
('Breeze', 'Breeze-Dark', 'Dracula', 'Raleigh', 'Yaru-dark', 'Yaru-light')
```

**Comment by maru0123-2004** [comment]
Oh...
Now I trying put theme in get_themes_directory's output....

**Comment by maru0123-2004** [comment]
It right... I was wrong. Sorry...
I get this on Windows:
```
('Adwaita',)
```
I think I would make pull request about this.

Thanks for your all helping....!
